title: gttrcr
description: physics studies the universe, mathematics ideas, philosophy the spirit
theme: minima
google_analytics: G-YT63QQMRMS
header_pages:
  - blog.md
  - oeis.md
minima:
  skin: dark
  social_links:
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/gttrcr/"
      title: linkedin
plugins:
  - jekyll-latex